version: '3'
services:
  employees-db:
    image: postgres:latest
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data1:/var/lib/postgresql/data

